version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./selfies:/app/selfies
    env_file:
      - .env
    depends_on:
      - mock-daraja

  mock-daraja:
    build: 
      context: .
      dockerfile: Dockerfile  # reuse base image to run mock via command
    command: ["python", "mock_daraja/server.py"]
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=development
