apiVersion: v1
kind: Secret
metadata:
  name: univ-vote-secret
type: Opaque
stringData:
  SECRET_KEY: "change-me"
  DATABASE_URL: "sqlite:///univvote.db"
  MPESA_CONSUMER_KEY: ""
  MPESA_CONSUMER_SECRET: ""
  MPESA_SHORTCODE: ""
  MPESA_PASSKEY: ""
